### ISSUE TITLE
cannot install:

### ISSUE THREAD

**Issue by francesco1119** [dholm/simpleguitk#6]
I've downloaded the file but when I try "python setup.py install" it says:

Installed /root/.pythonbrew/pythons/Python-2.7.7/lib/python2.7/site-packages/SimpleGUITk-1.1.3-py2.7.egg
Processing dependencies for SimpleGUITk==1.1.3
Searching for pygame>=1.9.0
Reading https://pypi.python.org/simple/pygame/
Reading http://www.pygame.org/
Reading http://www.pygame.org/download.shtml
No local packages or download links found for pygame>=1.9.0
error: Could not find suitable distribution for Requirement.parse('pygame>=1.9.0')

What to do?

**Comment by dholm** [comment]
You need to first install the package `pygame`.
